[package]
name = "rustcoalescence-algorithms-cuda"
version = "0.1.0"
authors = ["Juniper Tyree <juniper.tyree@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
almost-infinite-normal-dispersal-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/almost-infinite-normal-dispersal-scenario"]
almost-infinite-clark2dt-dispersal-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/almost-infinite-clark2dt-dispersal-scenario"]
almost-infinite-downscaled-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/almost-infinite-downscaled-scenario"]
non-spatial-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/non-spatial-scenario"]
spatially-explicit-uniform-turnover-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/spatially-explicit-uniform-turnover-scenario"]
spatially-explicit-turnover-map-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/spatially-explicit-turnover-map-scenario"]
spatially-implicit-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/spatially-implicit-scenario"]
wrapping-noise-scenario = ["rustcoalescence-algorithms-cuda-cpu-kernel/wrapping-noise-scenario"]

[dependencies]
necsim-core = { path = "../../../necsim/core" }
necsim-core-bond = { path = "../../../necsim/core/bond" }
necsim-impls-no-std = { path = "../../../necsim/impls/no-std" }
necsim-impls-std = { path = "../../../necsim/impls/std" }
necsim-impls-cuda = { path = "../../../necsim/impls/cuda" }
necsim-partitioning-core = { path = "../../../necsim/partitioning/core" }
rustcoalescence-scenarios = { path = "../../scenarios" }
rustcoalescence-algorithms = { path = "../" }
rustcoalescence-algorithms-cuda-cpu-kernel = { path = "./cpu-kernel" }
rustcoalescence-algorithms-cuda-gpu-kernel = { path = "./gpu-kernel" }

thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_state = "0.4"
serde_derive_state = "0.4"
rust-cuda = { git = "https://github.com/juntyr/rust-cuda", rev = "f2a377d", features = ["host"] }
