[package]
name = "rustcoalescence-algorithms-cuda-cpu-kernel"
version = "0.1.0"
authors = ["Juniper Tyree <juniper.tyree@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
almost-infinite-normal-dispersal-scenario = []
almost-infinite-clark2dt-dispersal-scenario = []
almost-infinite-downscaled-scenario = []
non-spatial-scenario = []
spatially-explicit-uniform-turnover-scenario = []
spatially-explicit-turnover-map-scenario = []
spatially-implicit-scenario = []
wrapping-noise-scenario = []

[dependencies]
necsim-core = { path = "../../../../necsim/core" }
necsim-core-bond = { path = "../../../../necsim/core/bond" }
necsim-impls-no-std = { path = "../../../../necsim/impls/no-std", features = ["cuda"] }
necsim-impls-cuda = { path = "../../../../necsim/impls/cuda" }
rustcoalescence-algorithms-cuda-gpu-kernel = { path = "../gpu-kernel" }

rust-cuda = { git = "https://github.com/juntyr/rust-cuda", rev = "f2a377d", features = ["host"] }
