#PBS -lselect=1:ncpus=2:mem=16gb
#PBS -lwalltime=01:00:00

module load mpi
module load anaconda3/personal

cd $HOME/necsim-rust

# anaconda-setup
# module load anaconda3/personal
# conda install libclang

./setup.sh

$HOME/.cargo/bin/cargo run --jobs 1 --release --target-dir target-replay

mpiexec $HOME/.cargo/bin/cargo run --jobs 1 --release --features rustcoalescence-algorithms-monolithic,rustcoalescence-algorithms-independent,necsim-partitioning-mpi --target-dir target-mpi
