#!/bin/bash
set -e

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none --profile minimal -y && \

source $HOME/.cargo/env

./setup.sh

cargo build --release --features rustcoalescence-algorithms-monolithic \
                      --features rustcoalescence-algorithms-independent

mkdir plugins

for f in target/release/deps/libnecsim_plugins*.so
    do cp "$f" "plugins/$(echo "$f" | sed s:target/release/deps/libnecsim_plugins_::)"
done

cargo install --path rustcoalescence --locked \
              --features rustcoalescence-algorithms-monolithic \
              --features rustcoalescence-algorithms-independent

rm -rf .cargo .vscode analysis binder necsim rust-cuda rustcoalescence \
       target third-party .gitpod.Dockerfile .gitpod.yml Cargo.lock \
       Cargo.toml rust-toolchain rustfmt.toml setup.sh
