#!/bin/bash
set -e

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- --default-toolchain none --profile minimal --no-modify-path -y

source $HOME/.cargo/env

./setup.sh

cargo build --release --features rustcoalescence-algorithms-monolithic \
                      --features rustcoalescence-algorithms-independent

mkdir plugins

ls target/release > ls1.txt
ls target/release/deps/*.so > ls2.txt

for f in target/release/deps/libnecsim_plugins*.so
    do echo 'cp "$f" "plugins/$(echo "$f" | sed s:target/release/deps/libnecsim_plugins::)"' >> cp.txt
    do cp "$f" "plugins/$(echo "$f" | sed s:target/release/deps/libnecsim_plugins::)"
done

rm -rf rustcoalescence

cp target/release/rustcoalescence .

rm -rf .cargo .rustup .vscode analysis binder necsim rust-cuda \
       target third-party .gitpod.Dockerfile .gitpod.yml Cargo.lock \
       Cargo.toml rust-toolchain rustfmt.toml setup.sh
